### ISSUE TITLE
Proposal: add overload that also accepts IServiceCollection

### ISSUE THREAD

**Issue by jbogard** [Particular/NServiceBus.Extensions.Hosting#22]
This is a bit of a weird edge case, but in order to correctly use the Microsoft Logging support, you have to resolve the `ILoggerFactory`:

```c#
Host.CreateDefaultBuilder(args)
    .ConfigureServices(services =>
    {
        var serviceProvider = services.BuildServiceProvider();

        var loggerFactory = serviceProvider.GetService<Microsoft.Extensions.Logging.ILoggerFactory>();
        var logFactory = LogManager.Use<MicrosoftLogFactory>();
        logFactory.UseMsFactory(loggerFactory);
    })
    .UseNServiceBus(...)
```

I'd rather do this inside the `UseNServiceBus` method, what do you think about adding an overload that accepts the additional `IServiceCollection` interface?

Or is logging just a little weird right now with this static business...

**Comment by WojcikMike** [comment]
Thanks @jbogard for raising this proposal. We added it to our internal backlog for future works. This issue will be updated when we decide to start working on it.

**Comment by danielmarbach** [comment]
@jbogard as far as I remember building the service provider as part of ConfigureServices is actually a design smell. I do think and agree with your hint that `Microsoft.Extensions.Logging` has basically introduced a shift in the MS ecosystem away from static logging towards "DI injected logging" and therefore our static logging seam is probably the culprit that enforces you to resolve at this early stage

**Comment by jbogard** [comment]
I'm OK closing this in favor of moving away from static logging, but oooooobviously that's a bit of a bigger deal.

**Comment by danielmarbach** [comment]
@jbogard see https://github.com/NServiceBusExtensions/NServiceBus.MicrosoftLogging/pull/75

I think you could also adopt a similar approach even if the PR is not merged officially into Simon's extension for MS logging

**Comment by danielmarbach** [comment]
@jbogard Simon merged the PR. So the logging support will be officially part of the MicrosoftLogging abstraction. are you ok if we close this?

**Comment by jbogard** [comment]
⚡️

**Comment by zlepper** [comment]
Sorry to necro this issue, but we have need for this, since a lot of our configuration relies on being able to access things when we are registering services. For now i'll just copy-paste your code out of the setup, since there is no reason why it couldn't just be done in the when you are configuring the service collection, rather than as part of the HostBuilder.

**Comment by tmasternak** [comment]
> Sorry to necro this issue, but we have need for this,

@zlepper do you have need to be able to pass `IServiceCollection` to `UseNServiceBus`?

**Comment by zlepper** [comment]
No, i need to access some thing before i know how to setup nservicebus. 

However i ended with quite a different workaround, since even loading things where i did it before causes issues, due to the lazy initialization of the `IMessageSession`, so instead i do the initialization manually, by mostly using your code, however i register NSB and start it in separate steps, so it is actually initializated before my other background services attempts to use it.
